import Head from "next/head";
import Home from "@components/templates/Home";
import { useEffect } from "react";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";

export default function HomePage() {
    const router = useRouter();
    const { isAuth } = useSelector((state) => {
        return state.user;
    });
    
    useEffect(()=>{
        if(!isAuth){
            router.push("/login")
        }else{
            router.push("/")
        }
    }, [isAuth]);

    return (
        <>
            <Head>
                <title>Shop With Us</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Home/>
            </main>
        </>
    );
}
