import Head from "next/head";
import Signup from "@components/templates/Auth/Signup";

export default function SignupPage() {
    return (
        <>
            <Head>
                <title>Sign Up</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Signup/>
            </main>
        </>
    );
}